### PR TITLE
Add avatars on the Bureaux page, toastError when office is already ex…

### PR DESCRIPTION
**Pull request by jakubkopco**

### CODE REVIEW

**Review by yoannfleurydev — CHANGES_REQUESTED** [review]
Please use `yarn` and not `npm` 🙂

**Comment by jakubkopco** [comment]
> The avatar is not at the right place.
> 
> Screenshot 2021-10-16 at 10 47 50 PM

There you want photoURL of currentUser?

**Comment by HugoPerard** [comment]
Like say Yoann, use yarn instead of npm (remove package-lock.json)

**Comment by jakubkopco** [comment]
@yoannfleurydev @HugoPerard Could you check last commit please? :)

**Comment by HugoPerard** [comment]
> @yoannfleurydev @HugoPerard Could you check last commit please? :)

There are feedbacks that steel uncorrected

**Comment by jakubkopco** [comment]
@HugoPerard I make some changes, please check it out :)

**Pull request merged**
